### ISSUE TITLE
Docker Hub public image

### ISSUE THREAD

**Issue by UnknownHero** [ryshi/docker-nginx#2]
Hello!
I fork your Dockerfile , make some changes and open repository on Docker Hub 
https://registry.hub.docker.com/u/unknownhero/ubuntu-nginx-lua/

So, if you get pull request https://github.com/Foxswily/docker-nginx/pull/1 and open repository on your Docker Hub account, i remove it from my accounts and you will be only one author :)

Thanks for work!

**Comment by ryshi** [comment]
hi,
  it's really a bug =.=", i'll update it
many thanks
